version: '3'
services:
  echo-server:
    image: ealen/echo-server:latest
    environment:
      - ENABLE__ENVIRONMENT=false
    ports:
      - 3000:80

  my-app:
    image: my-app
    ports:
      - 8090:80
    # Any additional configurations as needed
