version: '3'
services:
  echo-server:
    image: ealen/echo-server:latest
    environment:
      - ENABLE__ENVIRONMENT=false
    ports:
      - 3000:80

  my-app:
    image: my-app
    # Any additional configurations as needed
    ports:
      - 8081:80 # Map port 8081 of the host to port 80 of the container for the website
